
[window]

dimensions = { columns = 120, lines = 32}
padding = { x = 16, y = 16 }
opacity = 0.75
blur = true

[font]
normal = { family = "Iosevka", style = "Regular"}
size = 12

[colors]
# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#0A0E14'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[cursor]
style = { shape = "underline", blinking = "On" }

[keyboard]
bindings = [
    { key ="c", mods = "Control", mode = "AppCursor", action = "Copy" },
    { key ="v", mods = "Control", mode = "AppCursor", action = "Paste" },
]
