[colors]

[colors.primary]
foreground = "#d4d4d4"
background = "#121212"

[colors.normal]
red     = "#fdb2d4"
yellow  = "#f8e9a6"
green   = "#cdf6a0"
cyan    = "#aaeaf6"
blue    = "#98c4f3"
magenta = "#c4a9f8"

[colors.bright]
red     = "#fdb2d4"
yellow  = "#f8e9a6"
green   = "#cdf6a0"
cyan    = "#aaeaf6"
blue    = "#98c4f3"
magenta = "#c4a9f8"