
commands = [
    "plasma-apply-colorscheme BreezeDark && plasma-apply-colorscheme Carbon",
    "hyprctl reload"
]

[colorfiles]
hypr      = "Config/hypr/color.conf"
qml       = "Config/quickshell/theme/Color.qml"
rofi      = "Config/rofi/theme/color.rasi"
kitty     = "Config/kitty/color.conf"
alacritty = "Config/alacritty/color.toml"
kde       = "Config/kde/Carbon.colors"

dunst     = "Config/dunst/dunstrc"
